### ISSUE TITLE
Errore pagina login.php

### ISSUE THREAD

**Issue by DaniloPazz** [andreaval/Cohesion2PHPLibrary#1]
Warning: domdocument::domdocument() expects at least 1 parameter, 0 given in C:_server\wamp\www\iccs\Cohesion2PHPLibrary\cohesion2\Cohesion2.php on line 207

Fatal error: Call to undefined method domdocument::loadXML() in C:_server\wamp\www\iccs\Cohesion2PHPLibrary\cohesion2\Cohesion2.php on line 208

**Comment by andreaval** [comment]
**Call to undefined method domdocument::loadXML()**

mancano le librerie DOM XML nella configurazione di PHP. Controlla il file php.ini per vedere se vengono caricate correttamente.

**Comment by DaniloPazz** [comment]
Va bene grazie mille!
Il 05/lug/2016 13:45, "Andrea Vallorani" notifications@github.com ha
scritto:

**Comment by DaniloPazz** [comment]
Buongiorno, in che formato si presenta il token una volta effettuato il login? una stringa alfanumerica quanto lunga?

**Comment by andreaval** [comment]
in formato XML codificato base64. Puoi consultare l'appendice del file di documentazione README.doc

**Comment by DaniloPazz** [comment]
Ok grazie, un'ultima domanda: è possibile inserire le credenziali per accedere a cohesion in una pagina web poi ed effettuare il login direttamente da questa? Quindi se esiste un servizio nel WS che permette la restituzione del token ricevendo in entrata username e password? Grazie

**Comment by andreaval** [comment]
no, si può usare solo la pagina fornita dal servizio
