### ISSUE TITLE
PHP Fatal error: Call to a member function xpath() on null in... Cohesion2.php on line 286

### ISSUE THREAD

**Issue by mattymatty76** [andreaval/Cohesion2PHPLibrary#2]
Salve a tutti e complimenti per la libreria: veramente spettacolare ed utile, bravi!!!.
Purtroppo provando ad autenticarmi ricevo l'errore in oggetto, e da una prima analisi ho visto che nella variabile $result non c'è nulla come se fallisse il parsing... 

`$result = file_get_contents(self::COHESION2_WEB,false,$context);
$domXML = new DOMDocument;
$domXML->loadXML($result);`

non so magari sbaglio io qualcosa, giusto per completezza la macchina e' all'interno di una rete intranet ma e' stata abilitata per l'accesso ed anche il suo ip; tant'è che questo errore lo ricevo dopo essermi autenticato (e quindi aver raggiunto il server cohesion2) nella fase di ritorno dal server...
Aggiungo che e' stata anche installata la libreria php-xml ed abilitato allow_url_fopen 

grazie in anticipo per ogni eventuale chiarimento...

**Comment by andreaval** [comment]
Buonasera,
forse dipende dall'aggiornamento delle librerie SSL del server Cohesion. 
In pratica dovrebbe essere il problema segnalato in questo topic:
https://stackoverflow.com/questions/63235805/curl-openssl-error-141a318a-tls-process-ske-dhedh-key-too-small

Per risolvere devi sostituire nel file Cohesion2.php la variabile $context presente alle righe 169 e 251:

```js
$context  = stream_context_create(array(
          'http' => array(
                        'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                        'method'  => 'POST',
                        'content' => http_build_query($data),
           ),
));
```

 con il seguente codice:

```js
$context  = stream_context_create([
            'http' => [
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data),
            ],
            'ssl' => [
                'ciphers' => 'DEFAULT:!DH'
            ]
]); 
```

Fammi sapere se funziona
ciao

**Comment by mattymatty76** [comment]
Sei un grande!!! Funziona!!! 👍 
Grazie infinite!!!

**Comment by andreaval** [comment]
Ottimo! 👍
Grazie a te del feedback.
